config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'comments/index'
  end
  # Admin namespace for admin functionalities
  namespace :admin do
    resources :genres, only: [:index, :new, :create, :edit, :update, :show, :destroy]
    resources :homes, only: [:top]
    resources :posts
    resources :users, only: [:index, :show, :destroy] # 管理者用のユーザー一覧
    resources :groups, only: [:index, :show, :edit, :update, :destroy]
    resources :comments, only: [:index, :destroy]
  end
  
  # Devise routes for admin authentication
  devise_for :admins, controllers: { 
    sessions: 'admin/sessions'
  }

  # Devise routes for user authentication
  devise_for :users, controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }

  # Posts routes for general users
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
    
    resources :groups, only: [:create, :show, :update, :destroy] do
      member do
        get :members
        post :join
        # `post :join` により、参加申請はグループのメンバーシップに関連するため、 `groups` のメンバーに設定
      end
      
      resources :join_requests, only: [:index, :create, :update, :destroy] do
        member do
          post :approve
          post :reject
          post :re_request
          # `post :re_request` のルートを追加
        end
      end
      
      resources :group_memberships, only: [:index]
      # `group_memberships` のリソースを追加
    end
    
    member do
      patch :update_recruit_status
      # `patch :update_recruit_status` のルートを追加
    end
  end

  # Companies routes
  resources :companies, only: [:new]

  # User routes
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :followings
      get :followers
    end
    collection do
      get :mypage
    end
  end

  # Relationships routes
  resources :relationships, only: [:create, :destroy]

  # Static pages and search
  get 'homes/about'
  get 'search', to: 'search#index'

  # Genre routes for displaying users by genre
  resources :genres, only: [:index, :show] do
    member do
      get :users
    end
  end

  # Root path
  root 'homes#top'
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    user = User.find(params[:followed_id])
    
    if user
      current_user.follow(user)
      flash[:notice] = "フォローしました"
    else
      flash[:alert] = "ユーザーが見つかりません"
    end

    redirect_to user_path(user)
  end

  def destroy
    relationship = Relationship.find_by(id: params[:id])
    
    if relationship
      user = relationship.followed
      current_user.unfollow(user)
      flash[:notice] = "フォローを解除しました"
    else
      flash[:alert] = "フォロー関係が見つかりません"
    end

    redirect_to user_path(user)
  end

  def followings
    @user = User.find(params[:user_id])
    
    if @user
      @users = @user.followings
    else
      flash[:alert] = "ユーザーが見つかりません"
      @users = []
    end
  end

  def followers
    @user = User.find(params[:user_id])
    
    if @user
      @users = @user.followers
    else
      flash[:alert] = "ユーザーが見つかりません"
      @users = []
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", relationship_path(current_user.relationships.find_by(followed_id: user.id)), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", relationships_path(followed_id: user.id), method: :post, class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<div class="container mt-5">
  <h1 class="text-center">フォロー中のユーザー</h1>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <% if @users.any? %>
        <ul class="list-group">
          <% @users.each do |user| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <div>
                <%= link_to user.full_name, user_path(user), class: 'font-weight-bold' %>
                <p class="mb-0 text-muted"><%= user.company_name %></p>
              </div>
              <div>
                <% if current_user.following?(user) %>
                  <%= link_to 'フォロー外す', relationship_path(current_user.relationships.find_by(followed_id: user.id)), method: :delete, class: 'btn btn-sm btn-info' %>
                <% else %>
                  <%= link_to 'フォローする', relationships_path(followed_id: user.id), method: :post, class: 'btn btn-sm btn-success' %>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="text-center">フォロー中のユーザーはいません。</p>
      <% end %>
    </div>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class="container mt-5">
  <h1 class="text-center">フォロワー</h1>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <% if @users.any? %>
        <ul class="list-group">
          <% @users.each do |user| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <div>
                <%= link_to user.full_name, user_path(user), class: 'font-weight-bold' %>
                <p class="mb-0 text-muted"><%= user.company_name %></p>
              </div>
              <div>
                <% if current_user.following?(user) %>
                  <%= link_to 'フォロー外す', relationship_path(current_user.relationships.find_by(followed_id: user.id)), method: :delete, class: 'btn btn-sm btn-info' %>
                <% else %>
                  <%= link_to 'フォローする', relationships_path(followed_id: user.id), method: :post, class: 'btn btn-sm btn-success' %>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="text-center">フォロワーはいません。</p>
      <% end %>
    </div>
  </div>
</div>