config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'comments/index'
  end
  # Admin namespace for admin functionalities
  namespace :admin do
    resources :genres, only: [:index, :new, :create, :edit, :update, :show, :destroy]
    resources :homes, only: [:top]
    resources :posts
    resources :users, only: [:index, :show, :destroy] # 管理者用のユーザー一覧
    resources :groups, only: [:index, :show, :edit, :update, :destroy]
    resources :comments, only: [:index, :destroy]
  end
  
  # Devise routes for admin authentication
  devise_for :admins, controllers: { 
    sessions: 'admin/sessions'
  }

  # Devise routes for user authentication
  devise_for :users, controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }

  # Posts routes for general users
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
    
    resources :groups, only: [:create, :show, :update, :destroy] do
      member do
        get :members
        post :join
        # `post :join` により、参加申請はグループのメンバーシップに関連するため、 `groups` のメンバーに設定
      end
      
      resources :join_requests, only: [:index, :create, :update, :destroy] do
        member do
          post :approve
          post :reject
          post :re_request
          # `post :re_request` のルートを追加
        end
      end
      
      resources :group_memberships, only: [:index]
      # `group_memberships` のリソースを追加
    end
    
    member do
      patch :update_recruit_status
      # `patch :update_recruit_status` のルートを追加
    end
  end

  # Companies routes
  resources :companies, only: [:new]

  # User routes
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :followings
      get :followers
    end
    collection do
      get :mypage
    end
  end

  # Relationships routes
  resources :relationships, only: [:create, :destroy]

  # Static pages and search
  get 'homes/about'
  get 'search', to: 'search#index'

  # Genre routes for displaying users by genre
  resources :genres, only: [:index, :show] do
    member do
      get :users
    end
  end

  # Root path
  root 'homes#top'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  has_many :posts, dependent: :destroy
  
  has_many :created_groups, class_name: 'Group', foreign_key: 'creator_id'
  has_many :group_memberships
  has_many :joined_groups, through: :group_memberships, source: :group
  has_many :groups, through: :join_requests
  has_many :join_requests

  has_one_attached :profile_image

  validates :last_name, :first_name, presence: true
  validates :phone_number, presence: true, allow_blank: true
  validates :industry, presence: true

  def get_profile_image
    if profile_image.attached?
      profile_image
    else
      # デフォルト画像を返す場合、Rails の asset pipeline を利用してパスを指定する
      ActionController::Base.helpers.asset_path('no_image.jpg')
    end
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id)&.destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def full_name
    "#{last_name} #{first_name}".strip
  end

  def full_name_kana
    "#{last_name_kana} #{first_name_kana}".strip
  end
  
  def name
    full_name
  end

  def self.search_for(content, search_method)
    if content.present?
      content = convert_katakana_to_hiragana(content)
    end

    case search_method
    when 'partial'
      where('last_name LIKE :content OR first_name LIKE :content OR last_name_kana LIKE :content OR first_name_kana LIKE :content', content: "%#{content}%")
    else
      all
    end
  end

  private

  def self.convert_katakana_to_hiragana(text)
    text.tr("ァィゥェォカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン", "ぁぃぅぇぉかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん")
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'ユーザーが削除されました。'
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :include_genres, only: [:new, :create]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end
  
  def destroy
    super do |resource|
      # `super` が正常に処理された後に実行される
      if resource.destroyed?
        # サインアウト処理
        sign_out(resource)
        # 新規登録画面にリダイレクト
        redirect_to new_user_registration_path and return
      end
    end
  end

  protected

  # 新規登録後のリダイレクト先を指定
  def after_sign_up_path_for(resource)
    root_path # ホームのトップページにリダイレクト
  end

  private

  def include_genres
    @genres = Genre.all
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy, :followings, :followers]

  def index
    @users = User.all
  end

  def show
    @posts = @user.posts
  end

  def users_mypage
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'ユーザーが削除されました。'
  end

  def followings
    @title = "フォロー中"
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @users = @user.followers
    render 'relationships/followers'
  end

  def following_list
    @title = "フォロー中"
    @users = @user.followings
  end

  def follower_list
    @title = "フォロワー"
    @users = @user.followers
  end

  def mypage
    @user = current_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :company_name, :industry, :email, :phone_number, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<div class="container">
  <table class='table'>
    <tr>
      <td><%= image_tag @user.get_profile_image, size: '100x100' %></td>
    </tr>
    <tr>
      <th>name</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th>introduction</th>
      <td><%= @user.introduction %></td>
    </tr>
    <tr>
      <th>follows</th>
      <td><%= link_to @user.followings.count, followings_user_path(@user) %></td>
    </tr>
    <tr>
      <th>followers</th>
      <td><%= link_to @user.followers.count, followers_user_path(@user) %></td>
    </tr>
  </table>

  <div class="row mt-4">
    <div class="col-md-3">
      <h2>会社情報</h2>
      <p><strong>企業名:</strong> <%= @user.company %></p>
      <p><strong>業種:</strong> <%= @user.industry %></p>
    </div>
  </div>
</div>

  <div class='row'>
    <% if current_user != @user %>
      <div class="col">
        <%= render "relationships/btn", user: @user %>
      </div>
    <% else %>
      <div class="col">
        <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1 class="mb-4 text-center">ユーザー一覧</h1>

  <div class="table-responsive">
    <table class="table table-bordered table-striped text-center">
      <thead class="thead-dark">
        <tr>
          <th>名前</th>
          <th>会社名</th>
          <th>業種</th>
          <th>フォロー数</th>
          <th>フォロワー数</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.full_name, user_path(user), class: "text-primary" %></td>
            <td><%= user.company_name %></td>
            <td><%= user.industry %></td>
            <td>
              <%= link_to "フォロー数: #{user.followings.count}", followings_user_path(user), class: 'btn btn-primary' %>
            </td>
            <td>
              <%= link_to "フォロワー数: #{user.followers.count}", followers_user_path(user), class: 'btn btn-primary' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/mypage.html.erb
<div class="container mt-5">
  <div class="row">
    <!-- 左サイドバー: プロフィール情報 -->
    <div class="col-md-3">
      <div class="card mb-3">
        <div class="card-body text-center">
          <% if current_user.profile_image.attached? %>
            <%= image_tag current_user.profile_image, size: "150x150", class: 'img-thumbnail' %>
          <% else %>
            <%= image_tag 'no_image.jpg', size: "150x150", class: 'img-thumbnail' %>
          <% end %>
          <h3 class="mt-2"><%= current_user.full_name %></h3>
          <p class="text-muted"><%= current_user.company_name %></p>
          <p><%= current_user.email %></p>

          <!-- フォロー数とフォロワー数 -->
          <div class="mt-3">
            <%= link_to "フォロー数: #{current_user.followings.count}", followings_user_path(current_user), class: 'btn btn-primary btn-block' %>
          </div>
          <div class="mt-2">
            <%= link_to "フォロワー数: #{current_user.followers.count}", followers_user_path(current_user), class: 'btn btn-primary btn-block' %>
          </div>

          <!-- ユーザー編集ボタン -->
          <div class="mt-3">
            <%= link_to 'プロフィール編集', edit_user_registration_path, class: 'btn btn-primary btn-block' %>
          </div>

          <!-- アカウント削除ボタン -->
          <div class="mt-2">
            <%= button_to 'アカウント削除', registration_path(current_user), method: :delete, data: { confirm: '本当にアカウントを削除しますか？' }, class: 'btn btn-danger btn-block' %>
          </div>
        </div>
      </div>
    </div>

    <!-- メインコンテンツ: 投稿一覧 -->
    <div class="col-md-9">
      <h2>投稿一覧</h2>
      <ul class="list-group">
        <% current_user.posts.order(created_at: :desc).each do |post| %>
          <li class="list-group-item mb-3">
            <h4><%= link_to post.title, post_path(post) %></h4>
            <ul class="list-unstyled">
              <li><strong>募集業種:</strong> <%= post.industry %></li>
              <li><strong>期間:</strong> <%= post.duration %></li>
              <li><strong>場所:</strong> <%= post.location %></li>
              <li><strong>募集人数:</strong> <%= "#{post.current_recruits}/#{post.number_of_recruits}" %></li>
              <% if post.application_deadline.present? %>
                <li><strong>応募締切:</strong> <%= post.application_deadline.strftime("%Y-%m-%d") %> (残り <%= post.days_remaining %> 日)</li>
              <% else %>
                <li><strong>応募締切:</strong> 設定なし</li>
              <% end %>
            </ul>
            <span>
              <small><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></small>
            </span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <!-- ユーザーのプロフィール情報 -->
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">ユーザーのプロフィール</h4>
          <% if @user.profile_image.attached? %>
            <%= image_tag @user.profile_image, size: "150x150", class: 'img-thumbnail' %>
          <% else %>
            <%= image_tag 'no_image.jpg', size: "150x150", class: 'img-thumbnail' %>
          <% end %>
          <p><strong>名前:</strong> <%= @user.full_name %></p>
          <p><strong>会社名:</strong> <%= @user.company_name %></p>
          <%= render 'relationships/btn', user: @user %>
        </div>
      </div>
    </div>

    <!-- 投稿の一覧 -->
    <div class="col-md-8">
      <h1 class="text-center">投稿一覧</h1>
      <table class="table">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>募集人数</th>
            <th>期間</th>
            <th>場所</th>
          </tr>
        </thead>
        <tbody>
          <% @user.posts.each do |post| %>
            <tr>
              <td><%= link_to post.title, post_path(post) %></td>
              <td><%= post.recruit_status %></td>
              <td><%= post.duration %></td>
              <td><%= post.location %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<h1><%= @title %></h1>
<ul class="list-group">
  <% @users.each do |user| %>
    <li class="list-group-item">
      <%= link_to user.full_name, user_path(user) %>
    </li>
  <% end %>
</ul>